Add configuration class
ProctorU/json_api_responders pull request #4
Opened 2017-07-03 17:22 UTC by chevinbrown

- Now defaults to using `:jbuilder` instead of serializers.
- Still need tests

**Questions**
- Extra config options?
- Should the config class be an `attr_accessor`?

2017-07-06 14:54 UTC, dwilkins requested changes
Just one small change - :+1: for adding tests and infrastructure associated.   

A more thorough review of the existing code may be warranted.

2017-07-06 14:54 UTC, dwilkins commented on test/json_api_responders_test.rb
> +  # test 'rescue Unauthorized' do
:scissors:

2017-07-06 14:54 UTC, dwilkins commented on lib/json_api_responders/responder.rb
> +      return error_obj[:resource] = resource.model if resource.try(:model).present?
Need safe accessor &. for `resource` since it can be  nil from `respond_with_error`

2017-07-12 14:29 UTC, licatajustin requested changes

2017-07-12 14:29 UTC, licatajustin commented on json_api_responders.gemspec
> +  spec.authors = ['Kevin Brown']
Please keep the original author in here as well.

2017-07-12 14:29 UTC, licatajustin commented on lib/json_api_responders/responder.rb
> +      return error_obj[:resource] = resource.model if resource.try(:model).present?
Be careful with that operator, as it doesn't has 2.1 support. This gem will support 2.1+.

2017-07-12 14:29 UTC, licatajustin commented on README.md
> +Configure with an initializer to pick the default responder_type `:jbuilder` or `:serializer`. `:jbuilder` is the default.
This README needs detailed description of JSON format.

2017-07-12 14:36 UTC, dwilkins approved these changes

2020-09-21 17:58 UTC, closed without merging